[project]
name = "somnon"
description = "Rust-like Option and Result implementation"
authors = [{ name = "Eemil Kiviahde", email = "eemil.kiviahde@coldheart.dev" }]
version = "0.1.0"
requires-python = ">=3.11"
license = { file = "LICENSE.rst" }
readme = "README.md"
